name: Build, Test and Release
on: 
  push:
    tags:
      - '*'
      
jobs:
  build-test-upload-artifact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build
        run: npm run ng run pos-mobile:app-shell:production
        
      - name: Test
        run: |
          npm test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
        
      - name: Upload artifact
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: dist/pos-mobile/browser
          retention-days: 1
          
  release:
    runs-on: ubuntu-latest
    needs: build-test-upload-artifact
    steps:
      - uses: actions/checkout@v2
      
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: artifact
          path: artifact
          
      - name: Check downloaded artifact
        run: ls artifact
        
      - name: Get tag version
        id: TagVersion
        run: echo ::set-output name=version::${GITHUB_REF#refs/tags/}
        
      - name: Check tag version
        run: echo ${{ steps.TagVersion.outputs.version }}
        
      - name: Zip downloaded artifact
        uses: thedoctor0/zip-release@master
        with:
          filename: ${{ steps.TagVersion.outputs.VERSION }}.zip
          path: artifact/*
          
      - name: Check archived artifact
        run: ls
      
      - name: Get change log
        uses: scottbrenner/generate-changelog-action@master
        id: ChangeLog
          
      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          body: ${{ steps.ChangeLog.outputs.changelog }}
          files: ${{ steps.TagVersion.outputs.VERSION }}.zip
          
  
