name: Build, Test and Release
on: push
      
jobs:
  build-test-artifact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      
      - name: Install dependencies
        run: npm ci
      
      - name: Test
        run: echo $(git tag -l)
      
      - name: Get tag version
        id: TagVersion
        run: echo ::set-output name=version::$( git tag )
        
      - name: Check output
        env:
          RELEASE_VERSION: ${{ steps.TagVersion.outputs.version }}
        run: |
          echo $RELEASE_VERSION
          echo ${{ steps.TagVersion.outputs.version }}
          
  
