name: Build, Test and Release
on: 
  push:
    tags:
      - '*'
      
jobs:
  build-test-artifact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build
        run: npm run ng run pos-mobile:app-shell:production
        
      - name: Test
        run: |
          npm test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
      
      - name: Get tag version
        id: TagVersion
        run: echo ::set-output name=version::${GITHUB_REF#refs/tags/}
        
      - name: Check tag version
        run: echo ${{ steps.TagVersion.outputs.version }}
        
      - name: Upload artifact
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.TagVersion.outputs.version }}
          path: dist
          
  release:
    runs-on: ubuntu-latest
    needs: build-test-artifact
    steps:
      - uses: actions/checkout@v2
      
      - name: Get tag version
        id: TagVersion
        run: echo ::set-output name=version::${GITHUB_REF#refs/tags/}
        
      - name: Check tag version
        run: echo ${{ steps.TagVersion.outputs.version }}
      
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: ${{ steps.TagVersion.outputs.version }}
      
      - name: Get change log
        uses: scottbrenner/generate-changelog-action@master
        id: ChangeLog
      
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ steps.TagVersion.outputs.version }}
          body: ${{ steps.ChangeLog.outputs.changelog }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
  
